[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

[fmt]
bracket_spacing = true

[dependencies]
forge-std = "1.9.6"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
